version: '3'
services:
    docs:
        build:
            dockerfile: docker/docs.dockerfile
        working_dir: /docs/dwh
        container_name: docs
        user: docs
        restart: always
        environment:
            - DBT_USER=dbt
            - DBT_PW=example_pw
        depends_on:
            - dbtpostgres
        ports:
            - 8000:8000
        command: |
            bash -c "./wait_for_it.sh dbtpostgres:5432 -- dbt docs generate --vars \'{\"ds_no_dash\":\"\",\"ds\":\"2022-01-01\"}\' &&
            dbt docs serve --port 8000"

    flower:
        build:
            dockerfile: docker/airflow.dockerfile
        working_dir: /airflow
        container_name: flower
        user: airflow
        restart: always
        environment:
            - DBT_USER=dbt
            - DBT_PW=example_pw
        depends_on:
            - postgres
            - redis
            - webserver
        ports:
            - 5555:5555
        command: ./wait_for_it.sh webserver:8080 -- airflow celery flower

    webserver:
        build:
            dockerfile: docker/airflow.dockerfile
        working_dir: /airflow
        container_name: webserver
        user: airflow
        restart: always
        environment:
            - DBT_USER=dbt
            - DBT_PW=example_pw
        depends_on:
            - postgres
            - redis
            - dbtpostgres
        ports:
            - 8080:8080
        volumes:
            - ./airflow/dags:/airflow/dags
            - ./dwh:/airflow/dwh
        command: |
            bash -c "./wait_for_it.sh postgres:5432 -- echo 'done waiting for postgres' &&
            ./wait_for_it.sh dbtpostgres:5432 -- echo 'done waiting for dbtpostgres' &&
            source ./airflow_venv/bin/activate &&
            cd dwh &&
            dbt seed --vars \'{\"ds_no_dash\":\"\"}\' &&
            cd .. &&
            airflow db init &&
            airflow users create --role Admin --username admin --email admin@dairflow.com --firstname admin --lastname admin --password admin &&
            airflow webserver"

    scheduler:
        build:
            dockerfile: docker/airflow.dockerfile
        working_dir: /airflow
        container_name: scheduler
        user: airflow
        restart: always
        environment:
            - DBT_USER=dbt
            - DBT_PW=example_pw
        depends_on:
            - webserver
        volumes:
            - ./airflow/dags:/airflow/dags
            - ./dwh:/airflow/dwh
        command: ./wait_for_it.sh webserver:8080 -- airflow scheduler

    worker:
        build:
            dockerfile: docker/airflow.dockerfile
        working_dir: /airflow
        user: airflow
        restart: always
        environment:
            - DBT_USER=dbt
            - DBT_PW=example_pw
        depends_on:
            - scheduler
            - flower
        volumes:
            - ./airflow/dags:/airflow/dags
            - ./dwh:/airflow/dwh
        command: ./wait_for_it.sh flower:5555 -- airflow celery worker
    
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=example_pw
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=airflow
        expose:
            - 5432
        volumes:
            - 'db_data:/var/lib/postgresql/data'

    dbtpostgres:
        image: postgres:13
        container_name: dbtpostgres
        restart: always
        environment:
            - POSTGRES_USER=dbt
            - POSTGRES_PASSWORD=example_pw
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=dbt
        ports:
            - 5432:5432
        volumes:
            - 'dbt_data:/var/lib/postgresql/data'

    redis:
        image: redis:6.0
        container_name: redis
        restart: always
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        expose:
            - 6379

volumes:
    db_data: null
    dbt_data: null
