version: '3'
services:
    webserver:
        build:
            context: .
            dockerfile: cfg/local/airflow.dockerfile
        working_dir: /airflow
        container_name: webserver
        user: airflow
        restart: always
        env_file: cfg/local/.env
        depends_on:
            - postgres
            - redis
            - dbtpostgres
        ports:
            - 8080:8080
        volumes:
            - ./dags:/airflow/dags
            - ./plugins:/airflow/plugins
        command: |
            bash -c "source ./airflow_venv/bin/activate &&
            cd plugins/dbt &&
            dbt seed --vars '{\"ds_nodash\":\"\"}' &&
            cd ../.. &&
            airflow db init &&
            airflow users create --role Admin --username dev --email admin@dairflow.com --firstname dev --lastname lastname --password dev &&
            airflow webserver"

    scheduler:
        build:
            context: .
            dockerfile: cfg/local/airflow.dockerfile
        working_dir: /airflow
        container_name: scheduler
        user: airflow
        restart: always
        env_file: cfg/local/.env
        depends_on:
            - webserver
        volumes:
            - ./dags:/airflow/dags
            - ./plugins:/airflow/plugins
        command: bash -c "source ./airflow_venv/bin/activate && airflow scheduler"

    docs:
        build:
            context: .
            dockerfile: cfg/local/docs.dockerfile
        working_dir: /docs
        container_name: docs
        user: docs
        restart: always
        env_file: cfg/local/.env
        depends_on:
            - dbtpostgres
        ports:
            - 8000:8000
        volumes:
            - ./dags:/docs/dags
            - ./plugins:/docs/plugins
        command: |
            bash -c "dbt docs generate --profiles-dir plugins/dbt --project-dir plugins/dbt --vars '{\"ds_nodash\":\"\", \"ds\":\"\"}' &&
            dbt docs serve --profiles-dir plugins/dbt --project-dir plugins/dbt --port 8000"

    worker:
        build:
            context: .
            dockerfile: cfg/local/airflow.dockerfile
        working_dir: /airflow
        user: airflow
        restart: always
        env_file: cfg/local/.env
        depends_on:
            - scheduler
        volumes:
            - ./dags:/airflow/dags
            - ./plugins:/airflow/plugins
        command: bash -c "source ./airflow_venv/bin/activate && airflow celery worker"

    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=example_pw
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=airflow
        expose:
            - 5432
        volumes:
            - 'db_data:/var/lib/postgresql/data'

    dbtpostgres:
        image: postgres:13
        container_name: dbtpostgres
        restart: always
        environment:
            - POSTGRES_USER=dbt
            - POSTGRES_PASSWORD=example_pw
            - POSTGRES_HOST=dbtpostgres
            - POSTGRES_DB=dbt
        ports:
            - 5432:5432
        volumes:
            - 'dbt_data:/var/lib/postgresql/data'

    redis:
        image: redis:6.0
        container_name: redis
        restart: always
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        expose:
            - 6379

volumes:
    db_data: null
    dbt_data: null
