dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dbtpostgres
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PW') }}"
      port: 5432
      dbname: dbt
      schema: dev_hturner
      threads: 2
